{{- $root := . }}
  {{- $brokers := .Values.replicaCount | int }}
{{- range $i, $e := until $brokers  }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ template "redis-ha.fullname" $root }}-{{ $i }}
  labels:
    {{- include "redis-ha.labels" $root | nindent 4 }}
spec:
  type: {{ $root.Values.service.type }}
  ports:
    - port: 26379
      targetPort: 26379
      protocol: TCP
      name: sentinel
    - port: 6379
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "redis-ha.selectorLabels" $root | nindent 4 }}
{{- end }}
